### ISSUE TITLE
IE7-8: self-hosted font treated as inactive while it is actually rendered

### ISSUE THREAD

**Issue by andreyvolokitin** [typekit/webfontloader#144]
I am serving webfont from the same server as the document. I am loading it with the following js:

``` javascript
WebFont.load({
   custom: {
        families: ['Open+Sans+Condensed:300&subset=cyrillic,latin'],
        urls: ['fonts/OpenSansCondensed/fonts.css']
    }
});
```

CSS from fonts.css is as follows:

``` css
@font-face {
    font-family: 'Open Sans Condensed';
    src: url('opensans-condlight-webfont.eot');
    src: url('opensans-condlight-webfont.eot?#iefix') format('embedded-opentype'),
    url('opensans-condlight-webfont.woff') format('woff'),
    url('opensans-condlight-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
    }
```

In IE7-8 font is rendered, but treated by webfontloader as inactive (no active-class set, no active event fired).

At the same time if I loading the same font from google everything is working fine...

How can I solve it?
