### ISSUE TITLE
Selectively load custom fonts

### ISSUE THREAD

**Issue by SoftwareAndOutsourcing** [typekit/webfontloader#186]
Hi, I'm trying to selectively load fonts, so I can reduce the load times of a site. Here is my test code:

customfonts.html: 

``` html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta charset="UTF-8">
        <script src="http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js"></script>
        <script>
            function loadfont1() {
                WebFont.load({
                    custom: {
                        families: ['font1'],
                        urls: ['customfonts.css']
                    }
                });
            }
            function loadfont2() {
                WebFont.load({
                    custom: {
                        families: [],
                        urls: ['customfonts.css']
                    }
                });
            }
        </script>
        <style> 
            div { font-family: 'font1'} 
            span { font-family: 'font2'} 
        </style>
    </head>
    <body>
        <div onclick="loadfont1()">div</div>
        <span onclick="loadfont2()">span</span>
    </body>
</html>
```

customfonts.css:

``` css
@font-face {
    font-family: 'font1';
    src: url('../../fonts/font1.eot');
    src: url('../../fonts/font1?#iefix') format('embedded-opentype'),
         url('../../fonts/font1.woff') format('woff'),
         url('../../fonts/font1.ttf') format('truetype'),
         url('../../fonts/font1.svg#font1') format('svg');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'font2';
    src: url('../../fonts/font2.eot');
    src: url('../../fonts/font2?#iefix') format('embedded-opentype'),
         url('../../fonts/font2.woff') format('woff'),
         url('../../fonts/font2.ttf') format('truetype'),
         url('../../fonts/font2.svg#font2') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

No mater what I try, all the fonts in the css file are loaded. You can click on the div or on the span to reproduce this. Is this a bug? Is there any way to just load a single font from the css or should I make multiple ones or a dinamic one?
