### ISSUE TITLE
Load woff, woff2 font-face

### ISSUE THREAD

**Issue by DimitryDushkin** [typekit/webfontloader#271]
I'm using this config:
```js
WebFontConfig = {
      google: { families: [ 'Ubuntu:400:latin,cyrillic' ] }
    };
```

Which loads this css:
```css
@font-face {
  font-family: 'Ubuntu';
  font-style: normal;
  font-weight: 400;
  src: local('Ubuntu'), url(http://fonts.gstatic.com/s/ubuntu/v8/Rbrel7WusHF7uMf4pVxmeOvvDin1pK8aKteLpeZ5c0A.ttf) format('truetype');
}
```

I want only woff and woff2 for speed loading for modern browsers, but WebFont gives only link to `ttf` font. How to config it to load woff, woff2?
