### ISSUE TITLE
How to handle overridden generic font-families?

### ISSUE THREAD

**Issue by MaxDaten** [typekit/webfontloader#358]
Hi,

say we have this css:

```css
@font-face {
  font-family: serif;
  font-style: normal;
  font-weight: normal;
  src: url('../fonts/DejaVuSerif.otf');
}

body {
  font-family: serif;
}
```

First question: Is it legal to override the generic family 'serif' with a web font?

Chrome 55 and Safari 10 are ignoring these rules but a iOS WebView is not. Of course, when the browser is ignoring it, it's obviously the events aren't triggered. But even when the browser is not ignoring it, it is impossible to listen to the loading/active events.

Second question: Is it possible to listen to these events, when the browser is not ignoring it? Just using:

```js
WebFontConfig = {
  custom: {
     families: ['serif', 'sans-serif']
   }
}
```

Does not work, these families are always inactive, even when not ignored by the browser.

A bit of a context:

We are working with several epubs with custom web fonts, delivered by the publishers. We developed an app to display these epubs with epub.js in a WebView. epub.js uses an iframe to display the epubs content but the ready event is triggered too early before the font and layout are done. So I'm seeking for a solution to listen to some "font is loaded" event and want to use this project for this task. 

The said epubs have often this set of custom font-face rules with the overriding of 'sans-serif' and 'serif'. Unfortunately, iBooks and calibre are respecting these rules, and also the iOS WebView. But there are no events triggered by this framework.
